os.execute("command -v xcompmgr >/dev/null 2>&1 && xcompmgr -cf &")
os.execute("command -v dropbox >/dev/null 2>&1 && dropbox start")
os.execute("command -v thunderbird >/dev/null 2>&1 && thunderbird &")
os.execute("command -v icedove >/dev/null 2>&1 && icedove &")
os.execute("command -v gajim >/dev/null 2>&1 && gajim &")
os.execute("command -v skype >/dev/null 2>&1 && skype &")
os.execute("command -v solaar >/dev/null 2>&1 && solaar &")
os.execute("pkill -9 nm-applet;dbus-launch nm-applet &")
