os.execute("xcompmgr -cF &")
os.execute("dropbox start")
os.execute("thunderbird &")
os.execute("gajim &")
os.execute("skype &")
os.execute("volumeicon &")
os.execute("pkill -9 nm-applet;nm-applet &")
-- os.execute("urxvt256c -e irssi")
